import express, { Request, Response, NextFunction } from "express";
import cors from "cors";
import { getPrisma } from "./prisma.js";
import { requesterContext } from "./middleware/requester-context.js";
import { generateTicketNumber } from "./services/ticket-number.js";
import { upload, UnsupportedMimeTypeError } from "./middleware/upload.js";
import { saveAttachmentFile, generateSafeFileName } from "./services/attachmentStorage.js";
import { findOwnedTicket } from "./lib/ownership.js";

// The Express app is exported separately from app.listen() (see index.ts) so
// Supertest can import `app` without opening a port. Do not merge these files.
export const app = express();

app.use(cors());          // already wired: lets the Vite dev server call this API
app.use(express.json());

app.get("/api/health", (_req: Request, res: Response) => {
  res.status(200).json({
    status: 'ok',
    service: 'TokTickIT API',
  });
});


// ─── GET /api/categories ──────────────────────────────────
// §2 API Contract: active Categories for Create Ticket / My Tickets filter dropdowns.
// Auth header required: Yes.
// Response shape: { categories: [{ id, name }] }
// Only isActive=true rows (BR-21: references must be active).
app.get('/api/categories', requesterContext, async (_req: Request, res: Response) => {
  try {
    const prisma = getPrisma();
    const categories = await prisma.category.findMany({
      where: { isActive: true },
      orderBy: { id: 'asc' },
      select: { id: true, name: true },
    });
    res.status(200).json({ categories });
  } catch (err) {
    res.status(500).json({
      error: { code: 'SERVER_ERROR', message: 'Something went wrong. Please try again.' },
    });
  }
});

// ─── GET /api/related-systems ─────────────────────────────
// §3 API Contract: active Related Systems for Create Ticket dropdown.
// Auth header required: Yes.
// Response shape: { relatedSystems: [{ id, name }] }
// Only isActive=true rows (BR-21).
app.get('/api/related-systems', requesterContext, async (_req: Request, res: Response) => {
  try {
    const prisma = getPrisma();
    const relatedSystems = await prisma.relatedSystem.findMany({
      where: { isActive: true },
      orderBy: { id: 'asc' },
      select: { id: true, name: true },
    });
    res.status(200).json({ relatedSystems });
  } catch (err) {
    res.status(500).json({
      error: { code: 'SERVER_ERROR', message: 'Something went wrong. Please try again.' },
    });
  }
});

// ─── GET /api/dev-requesters ─────────────────────────────
// §1 API Contract: active Requesters for the Selection screen.
// No auth header required — this is the one endpoint reachable
// before a Requester is selected (api-spec §1).
// Returns only isActive=true rows (BR-02).
app.get('/api/dev-requesters', async (_req, res) => {
  try {
    const prisma = getPrisma();
    const requesters = await prisma.devRequester.findMany({
      where: { isActive: true },
      orderBy: { id: 'asc' },
      select: { id: true, fullName: true, email: true },
    });
    res.status(200).json({ requesters });
  } catch (err) {
    res.status(500).json({
      error: { code: 'SERVER_ERROR', message: 'Something went wrong. Please try again.' },
    });
  }
});

// ─── POST /api/tickets ───────────────────────────────────
// §4 API Contract: Create a Ticket for the current Requester.
// Auth header required: Yes.
// Content-Type: application/json (Phase 3: no attachments yet;
//   will switch to multipart/form-data in Phase 4 when attachments are added).
//
// Request body: { categoryId, relatedSystemId, summary, description, requestedPriority }
// Response 201: { ticket, attachments: [], attachmentFailures: [] }
//
// Business rules enforced:
//   BR-06  Ticket number generated by backend (TKT-{YYYY}-{6-digit})
//   BR-07  currentStatus always NEW
//   BR-08  itPriority and ticketOwnerId null at creation
//   BR-09  Ticket Date set by backend
//   BR-19  Summary: trimmed, 5-120 chars
//   BR-20  Description: trimmed, 20-2000 chars
//   BR-21  Category and RelatedSystem must reference active records
//   BR-22  Requested Priority: LOW, MEDIUM, HIGH only
//   BR-23  Duplicate submission prevention (submit button disabled)
//   BR-25  No attachment upload until ticket is committed
//   BR-26  Safe error messages, no internal leaks
//   BR-31  Partial failure handling (ticket survives attachment failures)

const VALID_PRIORITY_VALUES = ["LOW", "MEDIUM", "HIGH"] as const;

interface CreateTicketBody {
  categoryId?: unknown;
  relatedSystemId?: unknown;
  summary?: unknown;
  description?: unknown;
  requestedPriority?: unknown;
}

// Multer middleware: parse multipart body + validate files (BR-28, BR-29, BR-30)
// Order: multer → requesterContext → handler
//   multer runs first to reject invalid files early (413/415) before auth check
//   requesterContext validates auth after file parsing succeeds
app.post(
  "/api/tickets",
  upload.array("attachments", 5),
  requesterContext,
  async (req: Request, res: Response) => {
  try {
    const prisma = getPrisma();
    const body = req.body as CreateTicketBody;
    const requester = req.currentRequester!;

    // ─── Field-level validation ────────────────────────────────────
    const fieldErrors: Record<string, string> = {};

    // categoryId: required integer
    const categoryId = Number(body.categoryId);
    if (!Number.isInteger(categoryId) || categoryId <= 0) {
      fieldErrors.categoryId = "Category is required.";
    }

    // relatedSystemId: required integer
    const relatedSystemId = Number(body.relatedSystemId);
    if (!Number.isInteger(relatedSystemId) || relatedSystemId <= 0) {
      fieldErrors.relatedSystemId = "Related system is required.";
    }

    // summary: required, trimmed, 5-120 chars (BR-19)
    const summary = typeof body.summary === "string" ? body.summary.trim() : "";
    if (summary.length === 0) {
      fieldErrors.summary = "Summary is required.";
    } else if (summary.length < 5 || summary.length > 120) {
      fieldErrors.summary = "Summary must be between 5 and 120 characters.";
    }

    // description: required, trimmed, 20-2000 chars (BR-20)
    const description = typeof body.description === "string" ? body.description.trim() : "";
    if (description.length === 0) {
      fieldErrors.description = "Description is required.";
    } else if (description.length < 20 || description.length > 2000) {
      fieldErrors.description = "Description must be between 20 and 2000 characters.";
    }

    // requestedPriority: required, one of LOW/MEDIUM/HIGH (BR-22)
    const requestedPriority = typeof body.requestedPriority === "string"
      ? body.requestedPriority.trim().toUpperCase()
      : "";
    if (!VALID_PRIORITY_VALUES.includes(requestedPriority as any)) {
      fieldErrors.requestedPriority = "Requested priority must be one of LOW, MEDIUM, HIGH.";
    }

    // If any field-level errors, return 400 with fieldErrors (api-spec §4)
    if (Object.keys(fieldErrors).length > 0) {
      res.status(400).json({
        error: {
          code: "VALIDATION_ERROR",
          message: "Please fix the highlighted fields.",
          fieldErrors,
        },
      });
      return;
    }

    // ─── Reference validation (BR-21) ─────────────────────────────
    // Validate categoryId and relatedSystemId reference active records.
    // Must be done AFTER field-level validation to avoid DB queries for
    // invalid data.

    const [category, relatedSystem] = await Promise.all([
      prisma.category.findUnique({ where: { id: categoryId }, select: { id: true, name: true, isActive: true } }),
      prisma.relatedSystem.findUnique({ where: { id: relatedSystemId }, select: { id: true, name: true, isActive: true } }),
    ]);

    const refErrors: Record<string, string> = {};

    if (!category) {
      refErrors.categoryId = "Selected category does not exist.";
    } else if (!category.isActive) {
      refErrors.categoryId = "Selected category is no longer available.";
    }

    if (!relatedSystem) {
      refErrors.relatedSystemId = "Selected related system does not exist.";
    } else if (!relatedSystem.isActive) {
      refErrors.relatedSystemId = "Selected related system is no longer available.";
    }

    if (Object.keys(refErrors).length > 0) {
      // Use first ref error as the primary message (api-spec §4 INVALID_REFERENCE)
      const firstKey = Object.keys(refErrors)[0];
      res.status(400).json({
        error: {
          code: "INVALID_REFERENCE",
          message: refErrors[firstKey],
          fieldErrors: refErrors,
        },
      });
      return;
    }

    // ─── Generate ticket number (BR-06) with P2002 retry ──────────
    let ticketNumber: string | null = null;
    const MAX_TICKET_RETRIES = 3;

    for (let attempt = 0; attempt <= MAX_TICKET_RETRIES; attempt++) {
      try {
        ticketNumber = await generateTicketNumber(prisma);

        // Attempt to create the ticket
        const ticket = await prisma.ticket.create({
          data: {
            ticketNumber,
            requesterId: requester.id,
            categoryId,
            relatedSystemId,
            summary,
            description,
            requestedPriority: requestedPriority as "LOW" | "MEDIUM" | "HIGH",
            // BR-07: currentStatus defaults to NEW
            // BR-08: itPriority and ticketOwnerId are nullable
            // BR-09: createdAt defaults to now()
          },
          include: {
            requester: { select: { id: true, fullName: true } },
            category: { select: { id: true, name: true } },
            relatedSystem: { select: { id: true, name: true } },
          },
        });

        // ─── Process attachments (BR-28, BR-29, BR-31, BR-32) ─────
        // Attachments are processed AFTER ticket commit (Phase 2 of
        // transaction strategy from Prompt 1 analysis). If attachment
        // upload fails, the ticket remains valid (BR-31).
        const files = (req.files as Express.Multer.File[]) ?? [];
        const attachments: Array<{
          id: number;
          originalFileName: string;
          fileSizeBytes: number;
          mimeType: string;
          uploadedAt: string;
        }> = [];
        const attachmentFailures: Array<{
          originalFileName: string;
          reason: string;
        }> = [];

        for (const file of files) {
          // BR-32: safe storage filename = UUID + original extension
          const storedFileName = generateSafeFileName(file.originalname);

          // ─── Step 1: Write file to disk ─────────────────────────
          // If this fails, the file was never written — clean failure.
          let diskWriteOk = false;
          try {
            await saveAttachmentFile(file.buffer, storedFileName);
            diskWriteOk = true;
          } catch (diskErr) {
            // BR-31: partial failure — file write failed, no orphan
            attachmentFailures.push({
              originalFileName: file.originalname,
              reason: "UPLOAD_INTERRUPTED",
            });
            continue; // skip DB insert for this file
          }

          // ─── Step 2: Create attachment record in DB ─────────────
          // If this fails after disk write succeeded, we have an orphan
          // file on disk. This is acceptable in Lab 2 (file is harmless,
          // soft-deletion never removes files per BR-34) but the failure
          // reason is distinct from UPLOAD_INTERRUPTED for debugging.
          try {
            const attachment = await prisma.attachment.create({
              data: {
                ticketId: ticket.id,
                originalFileName: file.originalname,
                storedFileName,
                mimeType: file.mimetype,
                fileSizeBytes: file.size,
                uploadedByRequesterId: requester.id,
              },
            });

            attachments.push({
              id: attachment.id,
              originalFileName: attachment.originalFileName,
              fileSizeBytes: attachment.fileSizeBytes,
              mimeType: attachment.mimeType,
              uploadedAt: attachment.uploadedAt.toISOString(),
            });
          } catch (dbErr) {
            // File was written to disk but DB record failed — orphan file.
            // Reason is distinct from UPLOAD_INTERRUPTED so ops can
            // distinguish "file never written" from "file written but
            // record missing" when debugging.
            attachmentFailures.push({
              originalFileName: file.originalname,
              reason: "RECORD_CREATION_FAILED",
            });
          }
        }

        // Success — return 201 per api-spec §4
        res.status(201).json({
          ticket: {
            id: ticket.id,
            ticketNumber: ticket.ticketNumber,
            ticketDate: ticket.createdAt.toISOString(),
            requester: ticket.requester,
            category: ticket.category,
            relatedSystem: ticket.relatedSystem,
            summary: ticket.summary,
            description: ticket.description,
            requestedPriority: ticket.requestedPriority,
            itPriority: ticket.itPriority,
            currentStatus: ticket.currentStatus,
            ticketOwner: null, // BR-08: not yet assigned in Lab 2 (IT Staff workflow out of scope)
            resolutionSummary: ticket.resolutionSummary,
          },
          attachments,
          attachmentFailures,
        });
        return;
      } catch (err: any) {
        // P2002: unique constraint violation on ticketNumber → retry
        if (err?.code === "P2002") {
          continue;
        }
        // Other DB errors → throw to outer catch
        throw err;
      }
    }

    // All retries exhausted (should never happen in practice)
    res.status(500).json({
      error: {
        code: "SERVER_ERROR",
        message: "Something went wrong. Please try again.",
      },
    });
  } catch (err) {
    // BR-26: safe error, no internal details leaked
    res.status(500).json({
      error: {
        code: "SERVER_ERROR",
        message: "Something went wrong. Please try again.",
      },
    });
  }
});

// ─── GET /api/tickets ──────────────────────────────────────────────
// §5 API Contract: Paginated, searchable, filterable, sortable list of
// the current Requester's own Tickets (FR-07, FR-08).
// Auth header required: Yes.
//
// Query params: search, categoryId, requestedPriority, currentStatus,
//   sortBy, sortDir, page, pageSize
// Response: { tickets, pagination, filterOptions }
//
// Business rules enforced:
//   BR-07  currentStatus = NEW (only value in Lab 2)
//   BR-12  Ownership: only current Requester's tickets (WHERE requesterId)
//   BR-14  Search: case-insensitive partial match on ticketNumber OR summary
//   BR-15  Filters: AND logic; filterOptions from full ticket set
//   BR-16  Sort: default createdAt desc, tie-break id desc
//   BR-17  Pagination: page ≥ 1, pageSize ∈ {10,20,50}, clamped
//   BR-39  Empty vs no-results: totalItems=0 + no filters = empty state

const VALID_SORT_BY = ["createdAt", "updatedAt"] as const;
const VALID_SORT_DIR = ["asc", "desc"] as const;
const VALID_PAGE_SIZES = [10, 20, 50] as const;

app.get("/api/tickets", requesterContext, async (req: Request, res: Response) => {
  try {
    const prisma = getPrisma();
    const requester = req.currentRequester!;

    // ─── Parse & validate query params ────────────────────────────────
    const fieldErrors: Record<string, string> = {};

    const search = typeof req.query.search === "string" ? req.query.search.trim() : "";

    // categoryId: optional integer filter
    let categoryId: number | null = null;
    if (req.query.categoryId != null && req.query.categoryId !== "") {
      const parsed = Number(req.query.categoryId);
      if (!Number.isInteger(parsed) || parsed <= 0) {
        fieldErrors.categoryId = "categoryId must be a positive integer.";
      } else {
        categoryId = parsed;
      }
    }

    // requestedPriority: optional, one of LOW/MEDIUM/HIGH
    let requestedPriority: string | null = null;
    if (req.query.requestedPriority != null && req.query.requestedPriority !== "") {
      const raw = String(req.query.requestedPriority).trim().toUpperCase();
      if (!VALID_PRIORITY_VALUES.includes(raw as any)) {
        fieldErrors.requestedPriority = "requestedPriority must be one of LOW, MEDIUM, HIGH.";
      } else {
        requestedPriority = raw;
      }
    }

    // currentStatus: optional, one of NEW (Lab 2)
    let currentStatus: string | null = null;
    if (req.query.currentStatus != null && req.query.currentStatus !== "") {
      const raw = String(req.query.currentStatus).trim().toUpperCase();
      if (raw !== "NEW") {
        fieldErrors.currentStatus = "currentStatus must be NEW.";
      } else {
        currentStatus = raw;
      }
    }

    // sortBy: default createdAt
    let sortBy: string = "createdAt";
    if (req.query.sortBy != null && req.query.sortBy !== "") {
      const raw = String(req.query.sortBy).trim();
      if (!VALID_SORT_BY.includes(raw as any)) {
        fieldErrors.sortBy = "sortBy must be one of createdAt, updatedAt.";
      } else {
        sortBy = raw;
      }
    }

    // sortDir: default desc
    let sortDir: string = "desc";
    if (req.query.sortDir != null && req.query.sortDir !== "") {
      const raw = String(req.query.sortDir).trim().toLowerCase();
      if (!VALID_SORT_DIR.includes(raw as any)) {
        fieldErrors.sortDir = "sortDir must be one of asc, desc.";
      } else {
        sortDir = raw;
      }
    }

    // If any enum validation failed, return 400
    if (Object.keys(fieldErrors).length > 0) {
      res.status(400).json({
        error: {
          code: "VALIDATION_ERROR",
          message: "Invalid query parameter.",
          fieldErrors,
        },
      });
      return;
    }

    // page: clamped to ≥ 1 (BR-17)
    let page = Number(req.query.page);
    if (!Number.isFinite(page) || page < 1) page = 1;
    page = Math.floor(page);

    // pageSize: clamped to {10, 20, 50}, default 10 (BR-17)
    let pageSize = Number(req.query.pageSize);
    if (!Number.isFinite(pageSize) || !VALID_PAGE_SIZES.includes(pageSize as any)) {
      pageSize = 10;
    }

    // ─── Build Prisma where clause ───────────────────────────────────
    const where: any = {
      requesterId: requester.id, // BR-12: ownership
    };

    // BR-14: search — case-insensitive partial match on ticketNumber OR summary
    if (search) {
      where.OR = [
        { ticketNumber: { contains: search, mode: "insensitive" } },
        { summary: { contains: search, mode: "insensitive" } },
      ];
    }

    // BR-15: filters — AND logic
    if (categoryId != null) {
      where.categoryId = categoryId;
    }
    if (requestedPriority != null) {
      where.requestedPriority = requestedPriority;
    }
    if (currentStatus != null) {
      where.currentStatus = currentStatus;
    }

    // ─── Execute queries ─────────────────────────────────────────────
    // Two parallel queries:
    //   1. Filtered + paginated ticket list
    //   2. filterOptions from FULL ticket set (ignoring filters) (BR-15)

    const orderBy: any = [
      { [sortBy]: sortDir },
      { id: "desc" }, // BR-16: secondary tie-break
    ];

    const [tickets, totalItems, filterOptionsRaw] = await Promise.all([
      // Query 1: filtered + paginated tickets
      prisma.ticket.findMany({
        where,
        orderBy,
        skip: (page - 1) * pageSize,
        take: pageSize,
        select: {
          id: true,
          ticketNumber: true,
          createdAt: true,
          summary: true,
          requestedPriority: true,
          itPriority: true,
          currentStatus: true,
          ticketOwnerId: true,
          updatedAt: true,
          category: { select: { name: true } },
        },
      }),

      // Query 2: total count with same filters
      prisma.ticket.count({ where }),

      // Query 3: filterOptions from FULL ticket set (no search/filter/sort)
      // Uses only the ownership filter (requesterId = current)
      (async () => {
        const fullWhere = { requesterId: requester.id };
        const [cats, pris, stats] = await Promise.all([
          prisma.ticket.findMany({
            where: fullWhere,
            distinct: ["categoryId"],
            select: { category: { select: { id: true, name: true } } },
          }),
          prisma.ticket.findMany({
            where: fullWhere,
            distinct: ["requestedPriority"],
            select: { requestedPriority: true },
          }),
          prisma.ticket.findMany({
            where: fullWhere,
            distinct: ["currentStatus"],
            select: { currentStatus: true },
          }),
        ]);
        return {
          categories: cats
            .map((c) => c.category)
            .sort((a, b) => a.id - b.id),
          requestedPriorities: pris
            .map((p) => p.requestedPriority)
            .sort(),
          currentStatuses: stats
            .map((s) => s.currentStatus)
            .sort(),
        };
      })(),
    ]);

    const totalPages = Math.max(1, Math.ceil(totalItems / pageSize));

    // ─── Build response ───────────────────────────────────────────────
    res.status(200).json({
      tickets: tickets.map((t) => ({
        id: t.id,
        ticketNumber: t.ticketNumber,
        createdAt: t.createdAt.toISOString(),
        summary: t.summary,
        category: t.category.name,
        requestedPriority: t.requestedPriority,
        itPriority: t.itPriority,
        currentStatus: t.currentStatus,
        ticketOwner: null, // BR-8: not yet assigned in Lab 2
        updatedAt: t.updatedAt.toISOString(),
      })),
      pagination: {
        page,
        pageSize,
        totalItems,
        totalPages,
      },
      filterOptions: filterOptionsRaw,
    });
  } catch (err) {
    // BR-26: safe error, no internal details leaked
    res.status(500).json({
      error: {
        code: "SERVER_ERROR",
        message: "Something went wrong. Please try again.",
      },
    });
  }
});

// ─── GET /api/tickets/:ticketNumber ──────────────────────────────────
// §6 API Contract: Retrieve one Ticket owned by the current Requester,
// with its Attachments split into active and removed arrays.
// Auth header required: Yes.
//
// Business rules enforced:
//   BR-12  Ownership: only current Requester's ticket
//   BR-13  404 for non-existent OR cross-requester (no information leak)
//   BR-40  Re-fetches from backend on every page load (no cache trust)
//   BR-41  Ownership check via findOwnedTicket() single access point

app.get("/api/tickets/:ticketNumber", requesterContext, async (req: Request, res: Response) => {
  try {
    const requester = req.currentRequester!;
    const { ticketNumber } = req.params;

    // BR-41: ownership check through single access point
    const ticket = await findOwnedTicket(ticketNumber, requester.id);

    if (!ticket) {
      // BR-13: identical 404 for non-existent and cross-requester
      res.status(404).json({
        error: { code: "TICKET_NOT_FOUND", message: "Ticket not found." },
      });
      return;
    }

    // Fetch attachments, split into active and removed (api-spec §6)
    const allAttachments = await getPrisma().attachment.findMany({
      where: { ticketId: ticket.id },
      orderBy: { uploadedAt: "asc" },
      select: {
        id: true,
        originalFileName: true,
        fileSizeBytes: true,
        mimeType: true,
        uploadedAt: true,
        isRemoved: true,
        removedAt: true,
        removedReason: true,
      },
    });

    const active = allAttachments
      .filter((a) => !a.isRemoved)
      .map((a) => ({
        id: a.id,
        originalFileName: a.originalFileName,
        fileSizeBytes: a.fileSizeBytes,
        mimeType: a.mimeType,
        uploadedAt: a.uploadedAt.toISOString(),
      }));

    const removed = allAttachments
      .filter((a) => a.isRemoved)
      .map((a) => ({
        id: a.id,
        originalFileName: a.originalFileName,
        fileSizeBytes: a.fileSizeBytes,
        removedAt: a.removedAt?.toISOString() ?? null,
        removedReason: a.removedReason,
      }));

    // Success — return 200 per api-spec §6
    res.status(200).json({
      ticket: {
        id: ticket.id,
        ticketNumber: ticket.ticketNumber,
        ticketDate: ticket.createdAt.toISOString(),
        requester: ticket.requester,
        category: ticket.category,
        relatedSystem: ticket.relatedSystem,
        summary: ticket.summary,
        description: ticket.description,
        requestedPriority: ticket.requestedPriority,
        itPriority: ticket.itPriority,
        currentStatus: ticket.currentStatus,
        ticketOwner: null, // BR-08: not yet assigned in Lab 2
        resolutionSummary: ticket.resolutionSummary,
      },
      attachments: { active, removed },
    });
  } catch (err) {
    // BR-26: safe error, no internal details leaked
    res.status(500).json({
      error: {
        code: "SERVER_ERROR",
        message: "Something went wrong. Please try again.",
      },
    });
  }
});

// ─── Multer error handling middleware ──────────────────────────────────
// Catches errors thrown by multer middleware and maps to api-spec §4 responses:
//   - LIMIT_FILE_SIZE → 413 ATTACHMENT_TOO_LARGE
//   - LIMIT_FILE_COUNT → 400 VALIDATION_ERROR
//   - UnsupportedMimeTypeError → 415 UNSUPPORTED_ATTACHMENT_TYPE
//   - Other multer errors → 400
app.use((err: Error, _req: Request, res: Response, _next: NextFunction) => {
  // Multer-specific errors
  if (err.name === "MulterError") {
    const multerErr = err as any;

    if (multerErr.code === "LIMIT_FILE_SIZE") {
      res.status(413).json({
        error: {
          code: "ATTACHMENT_TOO_LARGE",
          message: "One or more files exceed the 5 MB limit.",
          fieldErrors: {
            attachments: multerErr.fieldName
              ? `${multerErr.fieldName} exceeds the 5 MB limit.`
              : "File exceeds the 5 MB limit.",
          },
        },
      });
      return;
    }

    if (multerErr.code === "LIMIT_FILE_COUNT") {
      res.status(400).json({
        error: {
          code: "VALIDATION_ERROR",
          message: "Too many files. Maximum 5 attachments allowed.",
          fieldErrors: {
            attachments: "Maximum 5 attachments allowed.",
          },
        },
      });
      return;
    }

    // Other multer errors (LIMIT_UNEXPECTED_FILE, etc.)
    res.status(400).json({
      error: {
        code: "VALIDATION_ERROR",
        message: "File upload error.",
        fieldErrors: {
          attachments: multerErr.message || "Invalid file upload.",
        },
      },
    });
    return;
  }

  // Custom MIME type rejection from our fileFilter (BR-28)
  if (err instanceof UnsupportedMimeTypeError) {
    res.status(415).json({
      error: {
        code: "UNSUPPORTED_ATTACHMENT_TYPE",
        message: "Only JPG, PNG, WEBP, and PDF files are allowed.",
        fieldErrors: {
          attachments: `${err.fileName} is not an allowed file type.`,
        },
      },
    });
    return;
  }

  // Non-multer errors — pass to Express default handler
  // (will result in 500 if unhandled)
  throw err;
});

export default app;
